import Navbar from '@/components/navbar/Navbar'
import './globals.css'
import { Inter,Poppins } from 'next/font/google'
import Footer from '@/components/footer/Footer'

const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({
  weight: '400',
  preload: false,
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
   
      <body className={poppins.className + ' container'}>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
